language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS
    on_success: change
    on_failure: always
    on_start: never

branches:
  only:
    - master

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0 WP_TRAVISCI=grunt
    - php: 7.0
      env: WP_VERSION=nightly WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - |
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
        composer global require "phpunit/phpunit=5.7.*"
      else
        composer global require "phpunit/phpunit=4.8.*"
      fi
    - |
      if [[ "$WP_TRAVISCI" == "grunt" ]] ; then
        npm install
        composer install
      fi

script:
    - phpunit
    - |
      if [[ "$WP_TRAVISCI" == "grunt" ]] ; then
        grunt default
      fi
